[VirtualKeyBoard] Fix AttributeError: 'VirtualKeyBoardstyle' object has no attribute 'nativeKeys'
(cherry picked from commit 368f071d0911fecfd8401be5998bc0640c4d94f0)